version: '3.8'
services:
  backendapp:
    container_name: backendapp
    image: frongfrank17/ctv-pr:v.deploy2amd64
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB: DBCTC
      URL_DB: 192.168.10.145
      PORT_DB: 3333
      DB_USER: "root"
      DB_PASSWORD: "P@ssw0rd"
